version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=workflow
      - POSTGRES_USER=workflow
      - POSTGRES_PASSWORD=workflow

