version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=workflow
      - POSTGRES_USER=workflow
      - POSTGRES_PASSWORD=workflow

  stroem-server:
    image: stroem-hub/stroem-server:dev
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - $PWD/files/workspace:/var/lib/stroem/workspace
      - $PWD/files/logs:/var/lib/stroem/logs
    environment:
      STROEM_DB_HOST: db
      STROEM_DB_DATABASE: workflow
      STROEM_DB_USERNAME: workflow
      STROEM_DB_PASSWORD: workflow
    ports:
      - "8080:8080"
    links:
      - postgres:db
    command:
      - "--config"
      - "/etc/stroem.yaml"
      - "-v"

  stroem-worker:
    image: stroem-hub/stroem-worker:dev
    build:
      context: .
      dockerfile: Dockerfile.worker
    links:
      - stroem-server:server
    command:
      - "--verbose"
      - "--server"
      - "http://server:8080"
