db:
  host: 127.0.0.1
  port: 5432
  database: workflow
  username: workflow
  password: workflow

logs:
  folder: /tmp/workflow-logs/


workspace:
  type: folder
  folder: ....
  poll_interval: 30

# workspace:
#   type: git
#   folder: ....
#   url:
#   ssh_key: ....
#   poll_interval: 30