db:
  host: 127.0.0.1
  port: 5432
  database: workflow
  username: workflow
  password: workflow

logs:
  folder: /var/lib/stroem/logs


workspace:
  folder: /var/lib/stroem/workspace

# workspace:
#   type: git
#   folder: ....
#   url:
#   ssh_key: ....
#   poll_interval: 30