db:
  host: 127.0.0.1
  port: 5432
  database: workflow
  username: workflow
  password: workflow

log_storage:
  type: local
  folder: /var/lib/stroem/logs
  cache_folder: /var/lib/stroem/logs-cache


workspace:
  type: folder
  folder: /var/lib/stroem/workspace

# workspace:
#   type: git
#   folder: ....
#   url:
#   ssh_key: ....
#   poll_interval: 30

auth:
  jwt_secret: secretstringgoeshere
  jwt_expiration: 30d
  refresh_token_secret: secretforhmac
  auth_signup: true
  initial_user:
    name: Admin
    email: admin@example.com
    provider_id: main
    password: 123
  providers:
    main:
      type: internal
      primary: true


